# Modular LLM Rationale and Food Science Report Generator

suppressPackageStartupMessages({
  library(DBI)
  library(RSQLite)
  library(httr2)
  library(jsonlite)
  library(readr)
  library(dplyr)
  library(purrr)
})

`%||%` <- function(x, y) if (is.null(x) || length(x) == 0) y else x

#' Generate LLM rationale and chef food science report for weekly meal plan
#'
#' @param weekly_plan_result Object returned by solve_mealplan_lexicographic()
#' @param api_key OpenRouter API key (defaults to OPENROUTER_API_KEY env var)
#' @param model Model identifier on OpenRouter
#' @param db_path SQLite database path to store report
#' @param output_md_path File path to write Markdown report
#' @param week_label Optional label for the week (e.g., "Week 37 - September")
#' @param mock_response Optional string or function returning string for testing without API calls
#' @return Generated Markdown report string
generate_mealplan_rationale <- function(weekly_plan_result,
                                         api_key = Sys.getenv("OPENROUTER_API_KEY"),
                                         model = "google/gemini-2.5-flash",
                                         db_path = "recipes.db",
                                         output_md_path = "output/weekly_mealplan_report.md",
                                         week_label = paste("Week of", Sys.Date()),
                                         mock_response = NULL) {

  schedule_df <- weekly_plan_result$schedule
  if (is.null(schedule_df) || !is.data.frame(schedule_df) || nrow(schedule_df) == 0) {
    stop("weekly_plan_result must contain a valid non-empty 'schedule' data frame.")
  }

  tier_scores <- weekly_plan_result$tier_scores %||% list()

  # Format schedule into concise summary text for LLM
  schedule_lines <- purrr::map_chr(seq_len(nrow(schedule_df)), function(r) {
    row <- schedule_df[r, ]
    sprintf(
      "- **%s** (Weekday: %s, F present: %s, Hot/Sunny: %s):\n  * Recipe: %s (ID: %s)\n  * Method: %s | Prep: %d min | Source: %s\n  * Matches -> Pantry/Garden: %d, Grocery Specials: %d, Seasonal: %d\n  * Nutrition -> Fiber: %.1fg, Protein: %.1fg, Mg: %.1fmg, Gut Score: %.1f",
      toupper(row$day),
      ifelse(isTRUE(row$is_weekday), "Yes", "No"),
      ifelse(isTRUE(row$f_present), "Yes", "No"),
      ifelse(isTRUE(row$weather_hot_sunny), "Yes", "No"),
      row$recipe_name,
      row$recipe_id,
      row$method %||% "standard",
      row$prep_time_min %||% 0,
      row$source %||% "unknown",
      row$fridge_garden_matches %||% 0,
      row$grocery_special_matches %||% 0,
      row$seasonal_matches %||% 0,
      row$fiber_g %||% 0,
      row$protein_g %||% 0,
      row$magnesium_mg %||% 0,
      row$gut_health_score %||% 0
    )
  })

  schedule_summary <- paste(schedule_lines, collapse = "\n\n")

  system_prompt <- "You are an expert executive chef, nutritionist, and culinary food scientist. Your task is to analyze an optimized 7-day weekly meal plan generated by a mathematical optimizer and produce an engaging, professional Markdown report in French or English (matching the recipe names)."

  user_prompt <- sprintf(
    "Here is the optimized weekly meal plan schedule for %s:\n\n%s\n\nOptimization Tier Performance Summary:\n- Nutrition Slack Penalty: %s\n- Pantry/Garden Matches: %s\n- Grocery Deal Matches: %s\n- Seasonal Matches: %s\n\nPlease generate a comprehensive report with two main sections:\n1. **Rationale & Scheduling Logic**: Explain why each meal is well-suited for its assigned day considering weeknight constraints, F presence, weather, and inventory/grocery specials.\n2. **Chef's Culinary & Food Science Enhancements**: Provide specific culinary improvements rooted in food science (e.g. Maillard reaction, acid/fat balance, fermentation, prep tips, flavor synergies) to elevate these 7 meals.\n\nFormat the response in clean, beautiful Markdown.",
    week_label,
    schedule_summary,
    tier_scores$nutrition_slack %||% "N/A",
    tier_scores$fridge_garden_matches %||% "N/A",
    tier_scores$grocery_special_matches %||% "N/A",
    tier_scores$seasonal_matches %||% "N/A"
  )

  # Check mock_response first
  report_markdown <- NULL
  if (!is.null(mock_response)) {
    report_markdown <- if (is.function(mock_response)) mock_response(user_prompt) else as.character(mock_response)
  } else if (!nzchar(api_key)) {
    message("No OPENROUTER_API_KEY provided. Generating structured local fallback report without LLM call.")
    report_markdown <- sprintf(
      "# Weekly Meal Plan Report - %s\n\n## 1. Rationale & Scheduling Summary\n\n%s\n\n*Note: Set OPENROUTER_API_KEY to generate deep LLM rationale and food science recommendations.*",
      week_label,
      schedule_summary
    )
  } else {
    tryCatch({
      req <- httr2::request("https://openrouter.ai/api/v1/chat/completions") |>
        httr2::req_headers(
          Authorization = paste("Bearer", api_key),
          `Content-Type` = "application/json"
        ) |>
        httr2::req_body_json(list(
          model = model,
          messages = list(
            list(role = "system", content = system_prompt),
            list(role = "user", content = user_prompt)
          )
        )) |>
        httr2::req_timeout(30)

      resp <- httr2::req_perform(req)
      content <- httr2::resp_body_json(resp, simplifyVector = FALSE)$choices[[1]]$message$content
      report_markdown <- content
    }, error = function(e) {
      warning("LLM API call failed: ", e$message, ". Falling back to local summary.")
      report_markdown <<- sprintf(
        "# Weekly Meal Plan Report - %s\n\n## 1. Rationale & Scheduling Summary (Fallback)\n\n%s\n\n*Error calling OpenRouter: %s*",
        week_label,
        schedule_summary,
        e$message
      )
    })
  }

  # Export to Markdown file
  if (!is.null(output_md_path) && nzchar(output_md_path)) {
    out_dir <- dirname(output_md_path)
    if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
    readr::write_file(report_markdown, output_md_path)
    message("Saved report markdown to: ", output_md_path)
  }

  # Export to SQLite database table mealplan_reports
  if (!is.null(db_path) && file.exists(db_path)) {
    tryCatch({
      conn <- DBI::dbConnect(RSQLite::SQLite(), db_path)
      on.exit(DBI::dbDisconnect(conn), add = TRUE)

      if (exists("init_recipe_db", mode = "function")) {
        init_recipe_db(db_path)
      }

      DBI::dbExecute(
        conn,
        "INSERT INTO mealplan_reports (week_label, report_markdown, model_used) VALUES (?, ?, ?)",
        params = list(week_label, report_markdown, model %||% "mock/local")
      )
      message("Saved report to database 'mealplan_reports' table in: ", db_path)
    }, error = function(e) {
      warning("Failed to save report to SQLite: ", e$message)
    })
  }

  return(report_markdown)
}
